stages:
  - deploy

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - librechat-production
  script:
    - cd /data/librechat/LibreChat
    - git pull origin main
    - docker compose -f deploy-compose.yml build --no-cache
    - docker compose -f deploy-compose.yml up -d --force-recreate --remove-orphans
    - docker image prune -f
  environment:
    name: production
    url: http://192.168.30.158